### ISSUE TITLE
/usr/bin/ld: cannot find -lluabindd

### ISSUE THREAD

**Issue by dikey94** [pedromateo/sdaver_qtlua_v2#1]
> /usr/bin/ld: cannot find -lluabindd

Libluabind-dev already installed. Ubuntu 14.04 LTS.

**Comment by pedromateo** [comment]
Hi,
please, try to find libluabindd in your system (e.g., by using "updatedb" and then "locate libluabindd").
Then, change the line to point to the new location.

**Comment by dikey94** [comment]
The library exists in "/usr/lib/debug/usr/lib/libluabindd.so.0.9.1". What should I change?

**Comment by dikey94** [comment]
`sudo ln -s /usr/lib/debug/usr/lib/libluabindd.so.0.9.1 /usr/lib/libluabindd.so`
works
